# Generated by Django 4.0.4 on 2022-05-28 17:56

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('materno', models.CharField(blank=True, max_length=30, null=True, verbose_name='Nombre')),
                ('celular', models.CharField(blank=True, max_length=30, null=True, verbose_name='Celular')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
                'db_table': 'Usuario',
                'ordering': ['first_name', 'last_name', 'materno'],
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=100, verbose_name='Servicio')),
                ('importe', models.DecimalField(decimal_places=2, default=0, max_digits=9, verbose_name='importe')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
            ],
            options={
                'verbose_name': 'Servicio',
                'verbose_name_plural': 'Servicios',
                'db_table': 'Servicio',
                'ordering': ['descripcion'],
                'unique_together': {('descripcion',)},
            },
        ),
        migrations.CreateModel(
            name='Recibo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nummero_recibo', models.CharField(max_length=30, verbose_name='Número de recibo')),
                ('edificio', models.CharField(choices=[('01', '01'), ('02', '02'), ('03', '03'), ('04', '04'), ('05', '05'), ('06', '06'), ('07', '07'), ('08', '08'), ('09', '09'), ('10', '10'), ('11', '11'), ('12', '12'), ('13', '13'), ('14', '14'), ('15', '15'), ('16', '16'), ('17', '17'), ('18', '18'), ('19', '19'), ('20', '20'), ('21', '21'), ('22', '22'), ('23', '23'), ('24', '24'), ('25', '25'), ('26', '26'), ('27', '27')], max_length=2, verbose_name='Edificio')),
                ('depto', models.CharField(choices=[('001', '001'), ('002', '002'), ('003', '003'), ('004', '004'), ('101', '101'), ('102', '102'), ('103', '103'), ('104', '104'), ('201', '201'), ('202', '202'), ('203', '203'), ('204', '204'), ('301', '301'), ('302', '302'), ('303', '303'), ('304', '304'), ('401', '401'), ('402', '402'), ('403', '403'), ('404', '404')], max_length=3, verbose_name='Departamento')),
                ('recibimos_de', models.CharField(max_length=90, verbose_name='Departamento')),
                ('importe', models.DecimalField(decimal_places=2, default=0, max_digits=9, verbose_name='Importe')),
                ('concepto', models.CharField(max_length=500, verbose_name='Concepto')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Recibo',
                'verbose_name_plural': 'Recibos',
                'db_table': 'Recibo',
                'ordering': ['edificio', 'depto', '-created'],
            },
        ),
        migrations.CreateModel(
            name='Edificio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=2, verbose_name='Edificio')),
                ('coordenadas', models.CharField(max_length=255, verbose_name='Coordenadas')),
                ('etiqueta_x', models.CharField(max_length=5, verbose_name='Etiqueta X')),
                ('etiqueta_y', models.CharField(max_length=5, verbose_name='Etiqueta Y')),
            ],
            options={
                'verbose_name': 'Edificio',
                'verbose_name_plural': 'Edificios',
                'db_table': 'Edificio',
                'ordering': ['numero'],
                'unique_together': {('numero',)},
            },
        ),
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edificio', models.CharField(choices=[('01', '01'), ('02', '02'), ('03', '03'), ('04', '04'), ('05', '05'), ('06', '06'), ('07', '07'), ('08', '08'), ('09', '09'), ('10', '10'), ('11', '11'), ('12', '12'), ('13', '13'), ('14', '14'), ('15', '15'), ('16', '16'), ('17', '17'), ('18', '18'), ('19', '19'), ('20', '20'), ('21', '21'), ('22', '22'), ('23', '23'), ('24', '24'), ('25', '25'), ('26', '26'), ('27', '27')], max_length=2, verbose_name='Edificio')),
                ('depto', models.CharField(choices=[('001', '001'), ('002', '002'), ('003', '003'), ('004', '004'), ('101', '101'), ('102', '102'), ('103', '103'), ('104', '104'), ('201', '201'), ('202', '202'), ('203', '203'), ('204', '204'), ('301', '301'), ('302', '302'), ('303', '303'), ('304', '304'), ('401', '401'), ('402', '402'), ('403', '403'), ('404', '404')], max_length=3, verbose_name='Departamento')),
                ('nombre', models.CharField(max_length=90, verbose_name='Nombre')),
                ('celular', models.CharField(blank=True, max_length=60, null=True, verbose_name='Celular')),
                ('telefono', models.CharField(blank=True, max_length=60, null=True, verbose_name='Teléfono')),
                ('correo', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Correo')),
                ('responsable', models.IntegerField(choices=[('1', 'Administrador'), ('2', 'Tesorero'), ('3', 'Inquilino')], verbose_name='Responsabilidad')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
            ],
            options={
                'verbose_name': 'Contacto',
                'verbose_name_plural': 'Contactos',
                'db_table': 'Contacto',
                'ordering': ['edificio', 'depto'],
                'unique_together': {('edificio', 'depto', 'nombre')},
            },
        ),
        migrations.CreateModel(
            name='Matto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edificio', models.CharField(choices=[('01', '01'), ('02', '02'), ('03', '03'), ('04', '04'), ('05', '05'), ('06', '06'), ('07', '07'), ('08', '08'), ('09', '09'), ('10', '10'), ('11', '11'), ('12', '12'), ('13', '13'), ('14', '14'), ('15', '15'), ('16', '16'), ('17', '17'), ('18', '18'), ('19', '19'), ('20', '20'), ('21', '21'), ('22', '22'), ('23', '23'), ('24', '24'), ('25', '25'), ('26', '26'), ('27', '27')], max_length=2, verbose_name='Edificio')),
                ('depto', models.CharField(choices=[('001', '001'), ('002', '002'), ('003', '003'), ('004', '004'), ('101', '101'), ('102', '102'), ('103', '103'), ('104', '104'), ('201', '201'), ('202', '202'), ('203', '203'), ('204', '204'), ('301', '301'), ('302', '302'), ('303', '303'), ('304', '304'), ('401', '401'), ('402', '402'), ('403', '403'), ('404', '404')], max_length=3, verbose_name='Departamento')),
                ('anio', models.IntegerField(verbose_name='Año')),
                ('mes', models.IntegerField(choices=[('1', 'Enero'), ('2', 'Febrero'), ('3', 'Marzo'), ('4', 'Abril'), ('5', 'Mayo'), ('6', 'Junio'), ('7', 'Julio'), ('8', 'Agosto'), ('9', 'Septiembre'), ('10', 'Octubre'), ('11', 'Noviembre'), ('12', 'Diciembre')], verbose_name='Mes')),
                ('recibo', models.CharField(blank=True, max_length=30, null=True, verbose_name='Número de recibo')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
                ('reciboFisico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.recibo')),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.servicio', verbose_name='servicio_matto')),
            ],
            options={
                'verbose_name': 'Matto',
                'verbose_name_plural': 'Mattos',
                'db_table': 'Matto',
                'ordering': ['edificio', 'depto', 'servicio', '-anio', '-mes'],
                'unique_together': {('edificio', 'depto', 'servicio', 'anio', 'mes')},
            },
        ),
    ]
