# Generated by Django 4.0.4 on 2022-05-28 19:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_rename_nummero_recibo_recibo_numero_recibo'),
    ]

    operations = [
        migrations.AddField(
            model_name='matto',
            name='usuario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
