# Generated by Django 4.0.4 on 2022-05-30 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_matto_mes'),
    ]

    operations = [
        migrations.AddField(
            model_name='matto',
            name='anio_mes1',
            field=models.CharField(default='000000', max_length=6, verbose_name='Año - mes'),
        ),
    ]
