# Generated by Django 4.0.4 on 2022-05-30 03:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_matto_anio_mes1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='matto',
            name='anio_mes1',
        ),
    ]
