# Generated by Django 4.0.4 on 2022-05-30 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_remove_matto_anio_mes1'),
    ]

    operations = [
        migrations.AddField(
            model_name='matto',
            name='anio_mes_str',
            field=models.CharField(default='000000', max_length=6, verbose_name='Año - mes'),
        ),
    ]
