# Generated by Django 4.0.4 on 2022-05-30 04:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_matto_anio_mes_str'),
    ]

    operations = [
        migrations.RenameField(
            model_name='matto',
            old_name='anio_mes_str',
            new_name='str_anio_mes',
        ),
    ]
