# Generated by Django 4.0.4 on 2022-05-30 04:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_rename_anio_mes_str_matto_str_anio_mes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='matto',
            old_name='str_anio_mes',
            new_name='hasta',
        ),
    ]
