# Generated by Django 4.0.4 on 2022-05-30 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_rename_str_anio_mes_matto_hasta'),
    ]

    operations = [
        migrations.AddField(
            model_name='matto',
            name='estatus',
            field=models.IntegerField(default=0, verbose_name='Estatus servicio'),
        ),
    ]
