# Generated by Django 4.0.4 on 2022-05-30 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_matto_estatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matto',
            name='estatus',
            field=models.IntegerField(choices=[('0', 'Pendiente'), ('1', 'Pagado')], default=0, verbose_name='Estatus servicio'),
        ),
    ]
