# Generated by Django 3.2.4 on 2022-07-21 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_auto_20220721_1537'),
    ]

    operations = [
        migrations.AddField(
            model_name='recibo',
            name='nom_usuario',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Nombre usuario'),
        ),
    ]
